# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - id: "calcli"
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    flags:
      - -mod=vendor

release:
  prerelease: auto


universal_binaries:
  - replace: true 


brews:
 - 
  name: calcli
  homepage: "https://github.com/ruokun-niu/calcli"