# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# https://medium.com/@ben.lafferty/deploying-go-cli-applications-316e9cca16a4

# set environment variables to be used in the build process
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - binary: calcli
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: autos

brews:
  - 
    name: calcli
    homepage: "https://github.com/ruokun-niu/calcli"
    tap:
      owner: ruokun-niu
      name: hoembrew-calcli
    commit_author:
      name: ruokun-niu
      email: halfsugardev7@gmail.com
# archives:
#   - format: tar.gz
#     name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
#     replacements:
#       replacements:
#         amd64: 64bit
#         386: 32bit
#         arm: ARM
#         arm64: ARM64
#         darwin: macOS
#         linux: Linux
#         windows: Windows
#       files:
#         - Readme.MD
#         - LICENSE



universal_binaries:
  - replace: true 


brews:
 - 
  name: calcli
  homepage: "https://github.com/ruokun-niu/calcli"